GeoscienceAustralia/GeodesyML

.gitmodules, .travis.yml, ci.sh, examples/MOBS.xml, examples/validate.sh, schema/Document.xsd, schema/FieldMeasurement.xsd, schema/Lineage.xsd, schema/Measurement.xsd, schema/ObservationSystem.xsd, schema/Project.xsd, schema/Quality.xsd, schema/ReferenceFrame.xsd, schema/contact.xsd, schema/dataStreams.xsd, schema/equipment.xsd, schema/geodeticEquipment.xsd, schema/geodeticMonument.xsd, schema/localInterferences.xsd, schema/monumentInfo.xsd, schema/siteLog.xsd
=> Add automatic validation of sample GeodesyML documents

.gitmodules, examples/MOBS-multiple-satellite-systems.xml, schema/equipment.xsd
=> Multiple satellite systems

examples/MOBS-more-info-multiple-datacenters.xml, schema/monumentInfo.xsd
=> Multiple data centers

schema/monumentInfo.xsd
=>  #26 remove hardCopyOnFile element

.gitignore, codelists/codeListRoles.xml, examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml, examples/schematron/codeListValidation.sch, examples/schematron/schematron/iso_schematron_skeleton_for_saxon.xsl, examples/schematron/schematron/iso_svrl_for_xslt2.xsl, examples/schematron/schematron/iso_svrl_for_xslt2_with_diagnostics.xsl, examples/schematron/schematronValidate.sh, schema/geodeticEquipment.xsd
* Currently antenna & receiver codelist
=>  #41 Setup schematron to validate codelist

schema/geodeticEquipment.xsd
* Following #41, a change went astray
=> bugfix-codelists-missing-antenna

.gitmodules, examples/validate.sh
=> 52 schemer

codelists/contacts-roles-codelists.xml, examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml, schemas/contact.xsd, schemas/geodesyML.xsd, tools/schematron/schematronValidate.sh
* Two blocks for Primary OR CI_Primary + Secondary OR CI_Secondary
* collapsed into Contact(primary or secondary) OR CI_Contact(primary or
* secondary) with "primary or secondary" being an attribute on these.
Resolve #24
=>  #24 Collapse Contacts

schemas/equipment.xsd
* xsd:string equivalent elements
* Soon these will be made codelists
=>   #70 to #100 - Drop enums and change to strings

examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml, schemas/equipment.xsd
* Changed another from ref to gml:validTime to gml:TimePeriodType as the
former is ineffective (there is no place to enter any data of value).
It is a period so can express Begin and End dates.
=> Make date in frequencyStandards work-able.

schemas/dataStreams.xsd, schemas/equipment.xsd, schemas/geodeticMonument.xsd, schemas/monumentInfo.xsd, schemas/quality.xsd
=> 79 to 100 change enumerated types 2

examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml, schemas/siteLog.xsd
=> Pluralise 2

examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml, schemas/commonTypes.xsd, schemas/contact.xsd, schemas/dataStreams.xsd, schemas/document.xsd, schemas/equipment.xsd, schemas/fieldMeasurement.xsd, schemas/geodesyML.xsd, schemas/geodeticEquipment.xsd, schemas/geodeticMonument.xsd, schemas/lineage.xsd, schemas/localInterferences.xsd, schemas/measurement.xsd, schemas/monumentInfo.xsd, schemas/observationSystem.xsd, schemas/project.xsd, schemas/quality.xsd, schemas/referenceFrame.xsd, schemas/siteLog.xsd
=> Bump version to 0.3

schemas/monumentInfo.xsd
This reverts commit 1a37d7c5ea5e113d1c9636b5839132e183d62c10.
=> Revert "Change siteIdentificationType to allow content in any order"

examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml
=>  #127 Reorder antennas and receivers by date

examples/MOBS-more-info-multiple-datacenters.xml, examples/MOBS-multiple-satellite-systems.xml, examples/MOBS.xml, schemas/commonTypes.xsd
DateInserted is mandatory, dateDeleted and deletedReason are optional.
=> Add change tracking to examples.

examples/validate.sh, schemas/catalog.xml
It think it makes more sense for the catalog file to be at the same level as our schemas and point down into the third party stuff
=> move catalog file up one level

tools/converter/log2xml.py, tools/converter/xml2log.py
deliveryPoint should be multiple lines
=> Multiple delivery points

codelists/antenna-receiver-codelists.tpl, codelists/antenna-receiver-codelists.xml
Only antenna and receiver code lists are currently in use.
Close #210.
=> Remove schema version number from code lists

pom.xml
Addition of GeodesyML 0.5 is a backwards-compatible change.
=> Bump minor version number

examples/0.5/20na_20161027.xml, examples/0.5/21na_20161027.xml, examples/0.5/MOBS.xml, examples/0.5/bboo_20170223.xml, examples/0.5/bcus_20150709.xml, examples/0.5/bdle_20150212.xml, examples/0.5/yar3_20140709.xml, schemas/geodesyml/0.5/monumentInfo.xsd, schemas/geodesyml/0.5/siteLog.xsd
=> Add SiteLocationPropertyType
